version: '3'

services:
  facesweb:
    image: faces-web:latest
    container_name: faces-web
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      # Settings network
      - HOST=0.0.0.0
      - PORT=3000
      - BROWSER_BASE_URL=https://example.com
      # BOOKSTACK
      - BOOKSTACK_KEY=
      - BOOKSTACK_API=http://bookstack:80/api/books
      - BOOKSTACK_URL=
      # HCAPTCHA
      - HCAPTCHA_SITE_KEY=
      - HCAPTCHA_SECRET_KEY=
      # MAIL SETTINGS
      - MAIL_HOST=
      - MAIL_PORT=587
      - MAIL_USER=
      - MAIL_PASSWORD=
      - MAIL_FROM=
      - MAIL_TO=
    # Deactivate watchtower auto update
    # labels:
    # - com.centurylinklabs.watchtower.enable=false
